# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bETR8F5omLhKnGQyijBm1NnMKqNeMChw
"""

# streamlit_app_py.py
import streamlit as st
import recommender_logic # This imports your recommender_logic.py

# --- Streamlit UI Configuration ---
st.set_page_config(
    page_title="Movie Recommender",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Main Application UI ---
st.title("🎬 Movie Recommender Engine")
st.markdown(
    "Discover movies similar to your favorites! "
    "Enter a movie title or identifier below and get recommendations based on content similarity."
)
st.markdown("---") # Visual separator

# Check if artifacts were loaded successfully by recommender_logic on import
if recommender_logic.artifacts_error:
    st.error(
        f"Failed to load recommender model artifacts: {recommender_logic.artifacts_error}\n"
        "Please ensure you have run `preprocess_data_py.py` and the artifact files "
        "(`cosine_sim_matrix.npy`, `movies_df_indexed.parquet`, `title_to_indices.joblib`) "
        "are in the same directory as the Streamlit app."
    )
    st.stop()
elif not recommender_logic.artifacts_loaded:
    st.error(
        "Recommender model artifacts are not loaded. The application might not work correctly. "
        "Please check the console for errors."
    )
    st.stop()

# --- User Input Section ---
col1, col2 = st.columns([3, 1])

with col1:
    # CHANGED variable name here:
    user_entered_movie_identifier = st.text_input(
        "Enter a movie title or ID:", # You can change the prompt too
        placeholder="e.g., The Matrix, Toy Story, Inception",
        help="Type the name or identifier of a movie you like."
    )

with col2:
    num_recs = st.slider(
        "Number of recommendations:",
        min_value=3,
        max_value=15,
        value=5,
        help="Choose how many recommendations you want to see."
    )

# --- Recommendation Button and Display ---
if st.button("✨ Get Recommendations", type="primary", use_container_width=True):
    # CHANGED variable name here:
    if user_entered_movie_identifier:
        with st.spinner(f"Finding recommendations for '{user_entered_movie_identifier}'..."):
            # Pass the user's input to the recommender logic
            recommendations = recommender_logic.recommend(user_entered_movie_identifier, num_recommendations=num_recs)

        st.markdown("---")
        if isinstance(recommendations, str):
            st.error(recommendations)
        elif recommendations:
            # CHANGED variable name in the success message:
            st.success(f"Here are {len(recommendations)} movies similar to '{user_entered_movie_identifier}':")
            for i, rec in enumerate(recommendations):
                st.markdown(f"**{i+1}.** {rec}")
        else:
            # CHANGED variable name in the warning message:
            st.warning(f"Sorry, we couldn't find any recommendations for '{user_entered_movie_identifier}'. Try a different movie.")
    else:
        st.warning("Oops! Please enter a movie identifier to get recommendations.")

# --- Sidebar Information ---
st.sidebar.header("ℹ️ About This App")
st.sidebar.info(
    "This Movie Recommender uses a content-based filtering approach. "
    "It analyzes movie features to find movies with similar characteristics."
)
st.sidebar.markdown("---")
st.sidebar.subheader("How it works:")
st.sidebar.markdown(
    """
    1.  **Data Preprocessing**: Movie data (using 'id' as the source title from CSV) is cleaned, and 'id' is renamed to 'title' for internal use. Textual features are combined.
    2.  **TF-IDF Vectorization**: Text features are converted into numerical vectors.
    3.  **Cosine Similarity**: The similarity between movies (using the internal 'title' identifier) is calculated.
    4.  **Recommendation**: When you enter a movie identifier, the app finds the most similar movies.
    """
)
st.sidebar.markdown("---")
st.sidebar.markdown("Built with [Streamlit](https://streamlit.io).")